package proyectoalgoritmos;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    private String dato;
    public Ventana2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void setmostrar(String dato){
        this.dato = dato;
        DatoNombre.setText(dato);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Music = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        DatoNombre = new javax.swing.JLabel();
        CampNombre = new javax.swing.JLabel();
        Estrellas = new javax.swing.JLabel();
        BtnDificil = new javax.swing.JButton();
        BtnRegular = new javax.swing.JButton();
        BtnFacil = new javax.swing.JButton();
        Fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Music.setBackground(new java.awt.Color(20, 61, 176));
        Music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_music.png"))); // NOI18N
        Music.setToolTipText("");
        Music.setBorder(null);
        Music.setContentAreaFilled(false);
        Music.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Music.setFocusCycleRoot(true);
        Music.setFocusPainted(false);
        Music.setFocusable(false);
        Music.setHideActionText(true);
        Music.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_muted.png"))); // NOI18N
        getContentPane().add(Music, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        Titulo.setFont(new java.awt.Font("Super Comic", 0, 50)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Seleccionar nivel");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        DatoNombre.setFont(new java.awt.Font("Freitag Trial Heavy", 0, 36)); // NOI18N
        DatoNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(DatoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 260, 50));

        CampNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campText.png"))); // NOI18N
        getContentPane().add(CampNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 350, 90));

        Estrellas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estrellas.png"))); // NOI18N
        getContentPane().add(Estrellas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 220, 70));

        BtnDificil.setBackground(new java.awt.Color(20, 61, 176));
        BtnDificil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BtnDificil.png"))); // NOI18N
        BtnDificil.setBorder(null);
        BtnDificil.setContentAreaFilled(false);
        BtnDificil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDificil.setRequestFocusEnabled(false);
        BtnDificil.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(BtnDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        BtnRegular.setBackground(new java.awt.Color(35, 46, 164));
        BtnRegular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BtnRegular.png"))); // NOI18N
        BtnRegular.setBorder(null);
        BtnRegular.setContentAreaFilled(false);
        BtnRegular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BtnRegular, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 260, 240));

        BtnFacil.setBackground(new java.awt.Color(35, 46, 164));
        BtnFacil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BtnFacil.png"))); // NOI18N
        BtnFacil.setBorder(null);
        BtnFacil.setContentAreaFilled(false);
        BtnFacil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnFacil.setRequestFocusEnabled(false);
        BtnFacil.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(BtnFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 270, 250));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo2.jpg"))); // NOI18N
        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDificil;
    private javax.swing.JButton BtnFacil;
    private javax.swing.JButton BtnRegular;
    private javax.swing.JLabel CampNombre;
    private javax.swing.JLabel DatoNombre;
    private javax.swing.JLabel Estrellas;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JButton Music;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
