/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoalgoritmos;

/**
 *
 * @author User
 */
public class Ventana4 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana4
     */
    public Ventana4() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        BtnAnterior1 = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        BtnConfig = new javax.swing.JButton();
        BtnMenu = new javax.swing.JButton();
        BtnMusic = new javax.swing.JButton();
        BtnHome1 = new javax.swing.JButton();
        Fondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 190, 140));

        BtnAnterior1.setBackground(new java.awt.Color(117, 194, 197));
        BtnAnterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnNext.png"))); // NOI18N
        BtnAnterior1.setBorder(null);
        BtnAnterior1.setContentAreaFilled(false);
        BtnAnterior1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BtnAnterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 260, 80));

        BtnAnterior.setBackground(new java.awt.Color(117, 194, 197));
        BtnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnPrevious.png"))); // NOI18N
        BtnAnterior.setBorder(null);
        BtnAnterior.setContentAreaFilled(false);
        BtnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BtnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 260, 80));

        BtnConfig.setBackground(new java.awt.Color(117, 194, 197));
        BtnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_config.png"))); // NOI18N
        BtnConfig.setBorder(null);
        BtnConfig.setContentAreaFilled(false);
        BtnConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BtnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 80, -1));

        BtnMenu.setBackground(new java.awt.Color(117, 194, 197));
        BtnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_menu.png"))); // NOI18N
        BtnMenu.setBorder(null);
        BtnMenu.setContentAreaFilled(false);
        BtnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        BtnMusic.setBackground(new java.awt.Color(117, 194, 197));
        BtnMusic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_music.png"))); // NOI18N
        BtnMusic.setBorder(null);
        BtnMusic.setContentAreaFilled(false);
        BtnMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMusic.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(BtnMusic, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 80, 70));

        BtnHome1.setBackground(new java.awt.Color(117, 194, 197));
        BtnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_home.png"))); // NOI18N
        BtnHome1.setBorder(null);
        BtnHome1.setContentAreaFilled(false);
        BtnHome1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BtnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        Fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo3.jpg"))); // NOI18N
        getContentPane().add(Fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnAnterior1;
    private javax.swing.JButton BtnConfig;
    private javax.swing.JButton BtnHome1;
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton BtnMusic;
    private javax.swing.JLabel Fondo4;
    private javax.swing.JLabel Logo;
    // End of variables declaration//GEN-END:variables
}
