/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoalgoritmos;

/**
 *
 * @author User
 */
public class Ventana3 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana4
     */
    public Ventana3() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnHome1 = new javax.swing.JButton();
        BtnConfig = new javax.swing.JButton();
        BtnNext = new javax.swing.JButton();
        BtnPrev = new javax.swing.JButton();
        BtnMusic = new javax.swing.JButton();
        BtnAudio1 = new javax.swing.JButton();
        BtnAudio2 = new javax.swing.JButton();
        BtnAudio3 = new javax.swing.JButton();
        BtnMenu1 = new javax.swing.JButton();
        Level1 = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        CarIMG = new javax.swing.JLabel();
        AppleIMG = new javax.swing.JLabel();
        AppleIMG2 = new javax.swing.JLabel();
        Contenedor = new javax.swing.JLabel();
        Fondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnHome1.setBackground(new java.awt.Color(117, 194, 197));
        BtnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_home.png"))); // NOI18N
        BtnHome1.setBorder(null);
        BtnHome1.setContentAreaFilled(false);
        BtnHome1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BtnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        BtnConfig.setBackground(new java.awt.Color(117, 194, 197));
        BtnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_config.png"))); // NOI18N
        BtnConfig.setBorder(null);
        BtnConfig.setContentAreaFilled(false);
        BtnConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BtnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 80, -1));

        BtnNext.setBackground(new java.awt.Color(117, 194, 197));
        BtnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_next.png"))); // NOI18N
        BtnNext.setBorder(null);
        BtnNext.setContentAreaFilled(false);
        BtnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNextActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        BtnPrev.setBackground(new java.awt.Color(117, 194, 197));
        BtnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_prev.png"))); // NOI18N
        BtnPrev.setBorder(null);
        BtnPrev.setContentAreaFilled(false);
        BtnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrevActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        BtnMusic.setBackground(new java.awt.Color(117, 194, 197));
        BtnMusic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_music.png"))); // NOI18N
        BtnMusic.setBorder(null);
        BtnMusic.setContentAreaFilled(false);
        BtnMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMusic.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(BtnMusic, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 80, 70));

        BtnAudio1.setBackground(new java.awt.Color(117, 194, 197));
        BtnAudio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_audio.png"))); // NOI18N
        BtnAudio1.setBorder(null);
        BtnAudio1.setContentAreaFilled(false);
        BtnAudio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAudio1.setDoubleBuffered(true);
        BtnAudio1.setMargin(new java.awt.Insets(20, 20, 20, 20));
        BtnAudio1.setMaximumSize(new java.awt.Dimension(60, 55));
        BtnAudio1.setMinimumSize(new java.awt.Dimension(60, 55));
        BtnAudio1.setPreferredSize(new java.awt.Dimension(60, 55));
        BtnAudio1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(BtnAudio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, 60));

        BtnAudio2.setBackground(new java.awt.Color(117, 194, 197));
        BtnAudio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_audio.png"))); // NOI18N
        BtnAudio2.setBorder(null);
        BtnAudio2.setContentAreaFilled(false);
        BtnAudio2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAudio2.setDoubleBuffered(true);
        BtnAudio2.setMargin(new java.awt.Insets(20, 20, 20, 20));
        BtnAudio2.setMaximumSize(new java.awt.Dimension(60, 55));
        BtnAudio2.setMinimumSize(new java.awt.Dimension(60, 55));
        BtnAudio2.setPreferredSize(new java.awt.Dimension(60, 55));
        BtnAudio2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(BtnAudio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, 70));
        BtnAudio2.getAccessibleContext().setAccessibleDescription("");

        BtnAudio3.setBackground(new java.awt.Color(117, 194, 197));
        BtnAudio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_audio.png"))); // NOI18N
        BtnAudio3.setBorder(null);
        BtnAudio3.setContentAreaFilled(false);
        BtnAudio3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAudio3.setDoubleBuffered(true);
        BtnAudio3.setMargin(new java.awt.Insets(20, 20, 20, 20));
        BtnAudio3.setMaximumSize(new java.awt.Dimension(60, 55));
        BtnAudio3.setMinimumSize(new java.awt.Dimension(60, 55));
        BtnAudio3.setPreferredSize(new java.awt.Dimension(60, 55));
        BtnAudio3.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(BtnAudio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, -1, 60));

        BtnMenu1.setBackground(new java.awt.Color(117, 194, 197));
        BtnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_menu.png"))); // NOI18N
        BtnMenu1.setBorder(null);
        BtnMenu1.setContentAreaFilled(false);
        BtnMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BtnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        Level1.setFont(new java.awt.Font("Super Comic", 1, 30)); // NOI18N
        Level1.setForeground(new java.awt.Color(204, 255, 255));
        Level1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Level1.setText("LEVEL 1");
        Level1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Level1.setFocusTraversalPolicyProvider(true);
        Level1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Level1.setName(""); // NOI18N
        getContentPane().add(Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 210, 40));

        Text1.setFont(new java.awt.Font("Super Comic", 1, 36)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text1.setText("CAR");
        Text1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Text1.setFocusTraversalPolicyProvider(true);
        Text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Text1.setName(""); // NOI18N
        getContentPane().add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 210, 40));

        Text2.setFont(new java.awt.Font("Super Comic", 1, 36)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text2.setText("HOUSE");
        Text2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Text2.setFocusTraversalPolicyProvider(true);
        Text2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Text2.setName(""); // NOI18N
        getContentPane().add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 210, 40));

        Text3.setFont(new java.awt.Font("Super Comic", 1, 36)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text3.setText("APPLE");
        Text3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Text3.setFocusTraversalPolicyProvider(true);
        Text3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Text3.setName(""); // NOI18N
        getContentPane().add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 210, 40));

        CarIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/car_min.png"))); // NOI18N
        getContentPane().add(CarIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 100, 100));

        AppleIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/house_min.png"))); // NOI18N
        getContentPane().add(AppleIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 100, 100));

        AppleIMG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apple_min.png"))); // NOI18N
        getContentPane().add(AppleIMG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 100, 100));

        Contenedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contenedor.png"))); // NOI18N
        getContentPane().add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 640, 500));

        Fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo3.jpg"))); // NOI18N
        getContentPane().add(Fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNextActionPerformed
        // TODO add your handling code here:
        Ventana4 v4 = new Ventana4();
        v4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnNextActionPerformed

    private void BtnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrevActionPerformed
        // TODO add your handling code here:
        Ventana2 v2 = new Ventana2();
        v2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPrevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppleIMG;
    private javax.swing.JLabel AppleIMG2;
    private javax.swing.JButton BtnAudio1;
    private javax.swing.JButton BtnAudio2;
    private javax.swing.JButton BtnAudio3;
    private javax.swing.JButton BtnConfig;
    private javax.swing.JButton BtnHome1;
    private javax.swing.JButton BtnMenu1;
    private javax.swing.JButton BtnMusic;
    private javax.swing.JButton BtnNext;
    private javax.swing.JButton BtnPrev;
    private javax.swing.JLabel CarIMG;
    private javax.swing.JLabel Contenedor;
    private javax.swing.JLabel Fondo4;
    private javax.swing.JLabel Level1;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    // End of variables declaration//GEN-END:variables
}
