package proyectoalgoritmos;
import java.applet.AudioClip;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Ventana5 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    private Clip clip;
    private boolean isPlaying = true;
    private int acumulador;
    public Ventana5() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void setResultado(int acumulador){
        this.acumulador = acumulador;
        ResultadoMonedas.setText(Integer.toString(acumulador));
    }
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Music = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        ResultadoMonedas = new javax.swing.JLabel();
        CampNombre = new javax.swing.JLabel();
        Estrellas = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Music.setBackground(new java.awt.Color(20, 61, 176));
        Music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_music.png"))); // NOI18N
        Music.setToolTipText("");
        Music.setBorder(null);
        Music.setContentAreaFilled(false);
        Music.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Music.setFocusCycleRoot(true);
        Music.setFocusPainted(false);
        Music.setFocusable(false);
        Music.setHideActionText(true);
        Music.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicActionPerformed(evt);
            }
        });
        getContentPane().add(Music, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        Titulo.setFont(new java.awt.Font("Super Comic", 0, 50)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("PUNTAJE TOTAL");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        ResultadoMonedas.setFont(new java.awt.Font("Super Comic", 0, 36)); // NOI18N
        ResultadoMonedas.setForeground(new java.awt.Color(255, 255, 255));
        ResultadoMonedas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultadoMonedas.setText("30 MONEDAS");
        getContentPane().add(ResultadoMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 310, 50));

        CampNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campText.png"))); // NOI18N
        getContentPane().add(CampNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 350, 90));

        Estrellas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estrellas.png"))); // NOI18N
        getContentPane().add(Estrellas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 220, 70));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo2.jpg"))); // NOI18N
        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicActionPerformed
        // TODO add your handling code here:
        AudioClip Ventana2;
        Ventana2 = java.applet.Applet.newAudioClip(getClass().getResource("/audio/music.wav"));
        Ventana2.play();
        
        
             boolean selected = Music.getModel().isSelected();  
                 if (selected =true) {
                     untoggled.setVisible(false);
                     Ventana2.play();
                }
                else{
                     toggled.setVisible(false);  
                     Ventana2.stop();
                }  
    }//GEN-LAST:event_MusicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana5().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CampNombre;
    private javax.swing.JLabel Estrellas;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JButton Music;
    private javax.swing.JLabel ResultadoMonedas;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables

    private static class toggled {

        private static void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public toggled() {
        }
    }
}
