/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoalgoritmos;

/**
 *
 * @author User
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreText = new javax.swing.JLabel();
        InputNombre = new javax.swing.JTextField();
        inputImg = new javax.swing.JLabel();
        BtnNombre = new javax.swing.JButton();
        BtnImage = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreText.setFont(new java.awt.Font("Freitag Trial Heavy", 0, 30)); // NOI18N
        NombreText.setForeground(new java.awt.Color(255, 255, 255));
        NombreText.setText("NOMBRE");
        getContentPane().add(NombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        InputNombre.setBackground(new java.awt.Color(255, 255, 255));
        InputNombre.setFont(new java.awt.Font("Super Comic", 0, 32)); // NOI18N
        InputNombre.setForeground(new java.awt.Color(51, 51, 51));
        InputNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        InputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNombreActionPerformed(evt);
            }
        });
        getContentPane().add(InputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 360, 40));

        inputImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/input.png"))); // NOI18N
        getContentPane().add(inputImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 430, 100));

        BtnNombre.setBackground(new java.awt.Color(255, 187, 0));
        BtnNombre.setFont(new java.awt.Font("Super Comic", 0, 35)); // NOI18N
        BtnNombre.setForeground(new java.awt.Color(128, 54, 29));
        BtnNombre.setText("ACEPTAR");
        BtnNombre.setBorder(null);
        BtnNombre.setBorderPainted(false);
        BtnNombre.setContentAreaFilled(false);
        BtnNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnNombre.setDefaultCapable(false);
        BtnNombre.setFocusPainted(false);
        BtnNombre.setFocusable(false);
        BtnNombre.setRequestFocusEnabled(false);
        BtnNombre.setVerifyInputWhenFocusTarget(false);
        BtnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNombreActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 220, 40));

        BtnImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn.png"))); // NOI18N
        BtnImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(BtnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 330, 100));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoE.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, 270));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNombreActionPerformed

    private void BtnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNombreActionPerformed
        // TODO add your handling code here:
        
        Ventana2 v2 = new Ventana2();
        v2.setmostrar(InputNombre.getText());
        v2.setVisible(true);
    }//GEN-LAST:event_BtnNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnImage;
    private javax.swing.JButton BtnNombre;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField InputNombre;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NombreText;
    private javax.swing.JLabel inputImg;
    // End of variables declaration//GEN-END:variables
}
